import 'package:flutter/material.dart';

@immutable
class CourseModule {
  const CourseModule({
    required this.id,
    required this.title,
    required this.tagline,
    required this.focus,
    required this.deliverable,
    required this.passGate,
    required this.icon,
    required this.worksheetAsset,
    required this.lessonPoints,
    required this.taskSteps,
  });

  final int id;
  final String title;
  final String tagline;
  final String focus;
  final String deliverable;
  final String passGate;
  final IconData icon;
  final String worksheetAsset;
  final List<String> lessonPoints;
  final List<String> taskSteps;
}

const courseModules = <CourseModule>[
  CourseModule(id: 1, title: 'Offer Foundation', tagline: 'Choose one market, one buyer, one service, one clear offer.', focus: 'Positioning', deliverable: 'A defined niche, primary buyer, bounded service, one-sentence offer, and 10 candidate clients.', passGate: 'The offer is understandable in under 15 seconds and at least five candidates are strong-fit opportunities.', icon: Icons.flag_outlined, worksheetAsset: 'worksheets/Module-1-Offer-Foundation-Worksheet.pdf', lessonPoints: ['Specific beats broad: one market and one buyer make research and outreach easier to evaluate.', 'Sell only work you can honestly deliver now; do not hide weak scope behind vague sales support.', 'A useful offer says who you help, what you do, and the outcome you are trying to create.'], taskSteps: ['Choose one B2B niche and one primary buyer.', 'Define what is included and what you will not promise yet.', 'Write one offer sentence and identify 10 real candidate clients.']),
  CourseModule(id: 2, title: 'ICP & Lead Research', tagline: 'Learn to tell a qualified prospect from a plausible-looking name.', focus: 'Research', deliverable: 'A specific prospect ICP and 10 leads supported by company, role, contact, and reason proof.', passGate: 'At least 9 of 10 audited leads pass all four proof checks.', icon: Icons.manage_search_outlined, worksheetAsset: 'worksheets/Module-2-ICP-Lead-Research-Worksheet.pdf', lessonPoints: ['Separate the client you want to serve from the prospects your client wants to sell to.', 'A lead needs company proof, role proof, contact proof, and a defensible reason for relevance.', 'Never guess contact details or invent a pain point just to complete a list.'], taskSteps: ['Define industry, geography, size, target roles, and exclusions.', 'Research 10 real prospects and record source evidence.', 'Audit every lead against the four-proof standard.']),
  CourseModule(id: 3, title: 'Outreach System', tagline: 'Build messages and calls that sound human, relevant, and safe.', focus: 'Outreach', deliverable: 'Cold email, follow-ups, direct message, call opener, bridge questions, and objection responses.', passGate: 'The outreach is specific, truthful, low-friction, and usable in a real conversation.', icon: Icons.send_outlined, worksheetAsset: 'worksheets/Module-3-Outreach-System-Worksheet.pdf', lessonPoints: ['Relevance comes before clever writing: show why this company or person was selected.', 'Use one clear next step instead of asking for too much in the first interaction.', 'Scripts are support rails, not a substitute for listening and answering the real question.'], taskSteps: ['Write the first-touch email or DM and follow-up sequence.', 'Build a cold-call opener plus bridge questions.', 'Prepare concise responses for the most likely objections.']),
  CourseModule(id: 4, title: 'Proof Package', tagline: 'Create credible proof before you have freelance client results.', focus: 'Proof', deliverable: 'Service brief, lead sample, outreach sample, campaign teardown, and a short voice/call sample.', passGate: 'Every proof asset is truthful, relevant, useful, and contains no invented results.', icon: Icons.workspace_premium_outlined, worksheetAsset: 'worksheets/Module-4-Proof-Package-Worksheet.pdf', lessonPoints: ['Beginner proof should demonstrate thinking and execution, not fake client outcomes.', 'A small relevant sample is more persuasive than a large generic portfolio.', 'Match proof to the risk the buyer is trying to evaluate: research, writing, calling, or process.'], taskSteps: ['Create a one-page service brief and 10-lead sample.', 'Prepare one outreach sample and one campaign teardown.', 'Record a short voice or call sample that sounds natural and professional.']),
  CourseModule(id: 5, title: 'Opportunity Pipeline', tagline: 'Build enough qualified opportunities to stop depending on luck.', focus: 'Pipeline', deliverable: 'A 50-opportunity pipeline across direct clients, targeted jobs, and warm opportunities.', passGate: 'The pipeline contains enough A and strong-B opportunities with clear next actions.', icon: Icons.account_tree_outlined, worksheetAsset: 'worksheets/Module-5-Opportunity-Pipeline-Worksheet.pdf', lessonPoints: ['One application is not a pipeline; enough qualified opportunities reduce desperation and bad decisions.', 'Mix acquisition lanes so one platform or channel cannot stop progress.', 'Every opportunity needs a fit reason, current status, and next action.'], taskSteps: ['Build 25 direct-client prospects.', 'Add 15 targeted jobs or projects and 10 legitimate warm opportunities.', 'Score fit and write the next action for every active opportunity.']),
  CourseModule(id: 6, title: 'First Live Outreach', tagline: 'Enter the market with targeted applications and direct outreach.', focus: 'Execution', deliverable: 'Real applications, direct-client first touches, warm messages where legitimate, and follow-ups.', passGate: 'The work was actually sent, tracked, and handled according to reply and compliance rules.', icon: Icons.rocket_launch_outlined, worksheetAsset: 'worksheets/Module-6-First-Live-Outreach-Worksheet.pdf', lessonPoints: ['The market teaches what worksheets cannot: real responses reveal targeting and communication quality.', 'Send targeted work, not random volume, and record what actually happened.', 'A real reply outranks the planned lesson—handle the opportunity first.'], taskSteps: ['Send the required targeted applications.', 'Send direct outreach to qualified prospects and legitimate warm messages where appropriate.', 'Record every touch, reply, follow-up, and next action.']),
  CourseModule(id: 7, title: 'Consistent Acquisition', tagline: 'Turn one live outreach day into a repeatable operating rhythm.', focus: 'Consistency', deliverable: 'A complete acquisition block: replenishment, new outreach, follow-up, practice, and metrics.', passGate: 'Due follow-ups are handled and activity remains targeted rather than random volume.', icon: Icons.repeat_outlined, worksheetAsset: 'worksheets/Module-7-Consistent-Acquisition-Worksheet.pdf', lessonPoints: ['Consistency is a system of replenishment, outreach, follow-up, and review—not nonstop cold messaging.', 'Follow-up debt makes the pipeline look busier than it really is.', 'Protect quality while building a rhythm you can actually sustain.'], taskSteps: ['Replenish qualified opportunities before the pipeline runs dry.', 'Complete new outreach and every due follow-up.', 'Log results and one communication practice block.']),
  CourseModule(id: 8, title: 'Targeting Improvement', tagline: 'Repair the market before blaming the message.', focus: 'Targeting', deliverable: 'A targeting audit, 10 stronger prospects, and one controlled targeting change.', passGate: 'The change is evidence-based and only one major targeting variable changes at a time.', icon: Icons.my_location_outlined, worksheetAsset: 'worksheets/Module-8-Targeting-Improvement-Worksheet.pdf', lessonPoints: ['Poor response can come from weak accounts, wrong roles, bad contactability, or bad timing—not only copy.', 'Replace weak prospects before increasing volume.', 'Change one major targeting variable so you can learn what caused the difference.'], taskSteps: ['Audit the weakest opportunities in the current pipeline.', 'Add 10 stronger prospects using clearer evidence.', 'Run one controlled targeting change and record the hypothesis.']),
  CourseModule(id: 9, title: 'Communication Improvement', tagline: 'Become more natural when the conversation leaves the script.', focus: 'Communication', deliverable: 'Opener reps, objection drills, appointment asks, and review of a real or recorded interaction.', passGate: 'The learner listens, answers the real concern, asks one question at a time, and recovers off-script.', icon: Icons.record_voice_over_outlined, worksheetAsset: 'worksheets/Module-9-Communication-Improvement-Worksheet.pdf', lessonPoints: ['Good sales communication is responsive: listen first, then answer what was actually said.', 'One clear question beats a stack of scripted questions.', 'Recovery after an unexpected response matters more than perfect memorization.'], taskSteps: ['Practice five opener variations without reading word-for-word.', 'Drill 10 realistic objections and three appointment asks.', 'Review one real or recorded interaction and identify one communication weakness.']),
  CourseModule(id: 10, title: 'Funnel Diagnosis', tagline: 'Find the largest leak instead of changing everything at once.', focus: 'Metrics', deliverable: 'A funnel snapshot, root-cause diagnosis, and one-variable experiment.', passGate: 'The bottleneck is supported by real evidence and the experiment has a defined observation window.', icon: Icons.monitor_heart_outlined, worksheetAsset: 'worksheets/Module-10-Funnel-Diagnosis-Worksheet.pdf', lessonPoints: ['A funnel is useful only when each stage is based on real activity and consistent definitions.', 'Find the largest meaningful drop before choosing what to change.', 'A one-variable experiment creates evidence; changing everything creates confusion.'], taskSteps: ['Calculate the current funnel from real activity.', 'Inspect examples around the largest drop-off.', 'Choose one hypothesis, one change, and one observation window.']),
  CourseModule(id: 11, title: 'Double Down on Evidence', tagline: 'Put more effort where real signals are strongest.', focus: 'Focus', deliverable: 'A strongest-lane decision, focused shortlist, relevant proof, and concentrated acquisition block.', passGate: 'Effort allocation follows evidence rather than preference or habit.', icon: Icons.trending_up_outlined, worksheetAsset: 'worksheets/Module-11-Double-Down-Worksheet.pdf', lessonPoints: ['Positive signals are more valuable than assumptions about which channel should work.', 'Concentrate effort where fit, replies, interviews, or useful conversations are strongest.', 'Customize proof for the lane rather than sending the same package everywhere.'], taskSteps: ['Choose the strongest acquisition lane using real evidence.', 'Build a focused shortlist and match proof to it.', 'Run a concentrated acquisition block without abandoning due follow-ups.']),
  CourseModule(id: 12, title: 'Discovery Preparation', tagline: 'Prepare for serious conversations without over-rehearsing.', focus: 'Discovery', deliverable: 'Company research, three priority questions, one useful artifact, and a next-step plan.', passGate: 'Preparation helps uncover the business problem without pretending to know what has not been verified.', icon: Icons.forum_outlined, worksheetAsset: 'worksheets/Module-12-Discovery-Preparation-Worksheet.pdf', lessonPoints: ['Discovery is for understanding the problem and process—not proving how smart you are.', 'Prepare a few high-value questions instead of a long interrogation list.', 'Know the desired next step before the conversation starts.'], taskSteps: ['Research the live company and contact.', 'Prepare three priority discovery questions and one relevant artifact.', 'Define the next step you want if the conversation is a fit.']),
  CourseModule(id: 13, title: 'Paid-Pilot Conversion', tagline: 'Make the first engagement small, clear, measurable, and paid.', focus: 'Conversion', deliverable: 'A bounded pilot with scope, metrics, responsibilities, compensation, and proposal.', passGate: 'Terms are explicit, risk is controlled, and no outcome outside the learner\'s control is guaranteed.', icon: Icons.handshake_outlined, worksheetAsset: 'worksheets/Module-13-Paid-Pilot-Conversion-Worksheet.pdf', lessonPoints: ['A first engagement should reduce risk for both sides by being small, bounded, and explicit.', 'Separate process metrics you control from sales outcomes you cannot guarantee.', 'Write responsibilities, payment, timing, and review conditions before work starts.'], taskSteps: ['Define pilot scope, duration, and deliverables.', 'Choose measurable process or funnel metrics and client responsibilities.', 'Write the proposal, compensation terms, and review point.']),
  CourseModule(id: 14, title: 'Review, Next Cycle & Graduation', tagline: 'Turn the first cycle into a system you can run again.', focus: 'Review', deliverable: 'Full funnel review, Keep/Change/Stop decisions, next hypothesis, and 30 fresh opportunities.', passGate: 'The learner can continue independently or has moved into onboarding and delivery for a real client.', icon: Icons.emoji_events_outlined, worksheetAsset: 'worksheets/Module-14-Review-Next-Cycle-Worksheet.pdf', lessonPoints: ['The first cycle is evidence, not a verdict on your ability.', 'Keep what produced useful signals, change one weak system, and stop low-value activity.', 'Graduation means you can run the acquisition loop independently—not that learning ends.'], taskSteps: ['Review the full funnel and important examples.', 'Write Keep / Change / Stop decisions and the next experiment.', 'Prepare 30 fresh qualified opportunities for the next cycle if no client is active.']),
];
