(() => {
  "use strict";
  const form=document.getElementById("website-request-form"); if(!form)return;
  const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
  const site=$("#sample-site"); let step=1; const total=5;
  const state={bg:"#070A10",primary:"#00F0FF",accent:"#8B5CFF",palette:"Cyber Cyan"};
  const requestId=`WEB-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${Math.random().toString(36).slice(2,6).toUpperCase()}`;
  $("#request-id").value=requestId; $("#form-next").value=`https://icharles.pages.dev/website-request-sent/?id=${encodeURIComponent(requestId)}`;
  const selected=n=>form.elements[n]?.value||""; const vals=n=>$$(`input[name="${n}"]:checked`,form).map(x=>x.value); const esc=s=>String(s||"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));
  const titles=["","1 OF 5 — WHAT DO YOU NEED?","2 OF 5 — TELL ME ABOUT IT","3 OF 5 — PICK THE LOOK","4 OF 5 — CHOOSE WHAT'S INCLUDED","5 OF 5 — SEND THE REQUEST"];
  const nextLabels=["","NEXT: TELL ME ABOUT IT →","NEXT: PICK THE LOOK →","NEXT: CHOOSE CONTENT →","NEXT: REVIEW + SEND →",""];
  const hints=["","Choose one website type, then continue.","Only the website name is required.","Pick what looks right. The preview updates instantly.","A sensible starter set is already selected.","Review your details, then send the free request."];

  function showStep(n,scroll=true){step=Math.max(1,Math.min(total,n)); $$(".wizard-step").forEach(x=>x.classList.toggle("active",Number(x.dataset.step)===step)); $("#progress-title").textContent=titles[step]; $("#progress-fill").style.width=`${step/total*100}%`; $("#wizard-back").disabled=step===1; $("#wizard-next").hidden=step===total; $("#wizard-submit").hidden=step!==total; $("#wizard-next").textContent=nextLabels[step]||"NEXT →"; $("#wizard-hint").textContent=hints[step]; if(step===5)updateVisibleSummary(); try{history.replaceState(null,"",`#builder-step-${step}`)}catch(_){} if(scroll)document.getElementById("builder").scrollIntoView({behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth",block:"start"}); }
  function validateCurrent(){ if(step===2){const name=$("#brand-name"); if(!name.value.trim()){name.focus(); name.reportValidity(); return false;}} return true; }
  $("#wizard-next").addEventListener("click",()=>{if(validateCurrent())showStep(step+1)}); $("#wizard-back").addEventListener("click",()=>showStep(step-1));

  const recommendations={
    "Business / Services":{pages:["Home","About","Services","Testimonials","Contact"],features:["Contact form","Scroll animation / motion","Basic SEO / social metadata"],text:"Home, About, Services, Reviews and Contact work well for a service business."},
    "Portfolio":{pages:["Home","About","Portfolio / Work","Contact"],features:["Contact form","Scroll animation / motion","Social links","Basic SEO / social metadata"],text:"Home, About, Work and Contact create a simple portfolio flow."},
    "Landing Page":{pages:["Home","FAQ","Contact"],features:["Contact form","Scroll animation / motion","Basic SEO / social metadata","Analytics"],text:"A focused landing page usually needs one main page, FAQ and a clear contact/action."},
    "Product / Showcase":{pages:["Home","About","Gallery","FAQ","Contact"],features:["Contact form","Scroll animation / motion","Social links","Basic SEO / social metadata","Analytics"],text:"A product site benefits from a clear overview, visuals, FAQ and a direct action."},
    "Restaurant / Local Business":{pages:["Home","About","Services","Gallery","Contact"],features:["Contact form","Map / location","Social links","Basic SEO / social metadata"],text:"Local businesses usually need clear services/menu information, photos, location and contact."},
    "Redesign Existing Website":{pages:["Home","About","Services","Contact"],features:["Contact form","Scroll animation / motion","Basic SEO / social metadata","Analytics"],text:"For a redesign, this is a safe starter structure. I will also review the existing site."}
  };
  function applyRecommendation(){const r=recommendations[selected("Website_Type")]||recommendations["Business / Services"]; $$('input[name="Pages[]"]').forEach(x=>x.checked=r.pages.includes(x.value)); $$('input[name="Features[]"]').forEach(x=>x.checked=r.features.includes(x.value)); $("#recommendation-text").textContent=r.text; updatePreview();}
  $$('input[name="Website_Type"]').forEach(x=>x.addEventListener("change",applyRecommendation));
  $$('[data-choose]').forEach(b=>b.addEventListener("click",()=>{const x=$(`input[name="Website_Type"][value="${b.dataset.choose}"]`);if(x){x.checked=true;applyRecommendation()}}));

  function summaryText(){return [`Request ${requestId}`,`Type: ${selected("Website_Type")}`,`Theme: ${selected("Theme")}`,`Palette: ${state.palette}`,`Font: ${selected("Font_Style")}`,`Text: ${selected("Text_Size")}`,`Motion: ${selected("Motion_Level")}`,`Corners: ${selected("Corner_Style")}`,`Pages: ${vals("Pages[]").join(", ")||"Not selected"}`,`Features: ${vals("Features[]").join(", ")||"Not selected"}`].join(" | ")}
  function updateVisibleSummary(){const type=selected("Website_Type").replace(" / Services",""); $("#request-summary-visible").querySelector("strong").textContent=`${type.toUpperCase()} · ${selected("Theme").toUpperCase()} · ${state.palette.toUpperCase()}`; const pages=vals("Pages[]"),features=vals("Features[]"); $("#request-summary-visible").querySelector("p").textContent=`${pages.join(", ")||"No pages selected"} · ${features.join(", ")||"No extra features selected"}`;}
  function updateSummary(){$("#design-summary").value=summaryText(); updateVisibleSummary()}

  function updatePreview(){
    const brand=$("#brand-name").value.trim()||"YOUR BRAND", industry=$("#industry").value.trim()||"YOUR BUSINESS // ONLINE", tagline=$("#tagline").value.trim()||"Your message becomes clear, memorable and easy to act on.", goal=$("#goal").value, type=selected("Website_Type");
    const theme=$("input[name='Theme']:checked"),font=$("input[name='Font_Style']:checked"),size=$("input[name='Text_Size']:checked"),radius=$("input[name='Corner_Style']:checked"),motion=$("input[name='Motion_Level']:checked");
    site.dataset.theme=theme?.dataset.theme||"future";site.dataset.font=font?.dataset.font||"modern";site.dataset.size=size?.dataset.size||"balanced";site.dataset.radius=radius?.dataset.radius||"sharp";site.dataset.motion=motion?.dataset.motion||"dynamic";site.style.setProperty("--site-bg",state.bg);site.style.setProperty("--site-primary",state.primary);site.style.setProperty("--site-accent",state.accent);
    if(["light","minimal"].includes(site.dataset.theme)&&state.bg.toLowerCase()==="#070a10")site.style.setProperty("--site-bg","#f4f4f2");
    $("#preview-brand").textContent=brand.toUpperCase();$("#sample-mark").textContent=brand.charAt(0).toUpperCase()||"Y";$("#preview-industry").textContent=industry.toUpperCase();$("#preview-tagline").textContent=tagline;
    const headline={"Business / Services":"MAKE YOUR BUSINESS EASY TO UNDERSTAND.","Portfolio":"PUT YOUR BEST WORK IN FRONT OF PEOPLE.","Landing Page":"ONE OFFER. ONE CLEAR NEXT STEP.","Product / Showcase":"GIVE YOUR PRODUCT A HOME WORTH VISITING.","Restaurant / Local Business":"HELP LOCAL CUSTOMERS FIND AND CHOOSE YOU.","Redesign Existing Website":"MAKE THE WEBSITE FEEL CURRENT AGAIN."}[type]||"A WEBSITE THAT FEELS LIKE YOUR BRAND."; const words=headline.split(" "),cut=Math.max(2,Math.floor(words.length*.52));$("#preview-title").innerHTML=`${esc(words.slice(0,cut).join(" "))}<br><em>${esc(words.slice(cut).join(" "))}</em>`;
    $("#preview-cta").textContent={"Contact / inquire":"GET IN TOUCH","Book an appointment":"BOOK NOW","View my work":"VIEW WORK","Learn about my business":"LEARN MORE","Visit my location":"FIND US","Buy / ask about a product":"VIEW PRODUCT","Something else":"START HERE"}[goal]||"GET IN TOUCH";
    $("#read-theme").textContent=selected("Theme").replace(" Dark","").toUpperCase();$("#read-palette").textContent=state.palette.toUpperCase();$("#read-type").textContent=type.replace(" / Services","").toUpperCase();$("#primary-color-hidden").value=state.primary;$("#accent-color-hidden").value=state.accent;$("#background-color-hidden").value=state.bg;$("#palette-name").value=state.palette;updateSummary();saveDraft();
  }
  $$(".palette-option").forEach(btn=>btn.addEventListener("click",()=>{$$(".palette-option").forEach(x=>x.classList.remove("active"));btn.classList.add("active");state.palette=btn.dataset.name;state.bg=btn.dataset.bg;state.primary=btn.dataset.primary;state.accent=btn.dataset.accent;$("#color-bg").value=state.bg;$("#color-primary").value=state.primary;$("#color-accent").value=state.accent;updatePreview()}));
  [["#color-bg","bg"],["#color-primary","primary"],["#color-accent","accent"]].forEach(([id,key])=>$(id).addEventListener("input",e=>{state[key]=e.target.value;state.palette="Custom";$$(".palette-option").forEach(x=>x.classList.remove("active"));updatePreview()}));
  form.addEventListener("input",updatePreview); form.addEventListener("change",updatePreview);
  $$('[data-view]').forEach(btn=>btn.addEventListener("click",()=>{$$('[data-view]').forEach(x=>x.classList.remove("active"));btn.classList.add("active");site.classList.toggle("mobile",btn.dataset.view==="mobile")}));
  $("#choose-for-me").addEventListener("click",()=>{const type=selected("Website_Type"); const choice={"Business / Services":["Clean Light","Ocean"],"Portfolio":["Premium Dark","Midnight Gold"],"Landing Page":["Bold Creative","Rose"],"Product / Showcase":["Futuristic Dark","Cyber Cyan"],"Restaurant / Local Business":["Elegant","Midnight Gold"],"Redesign Existing Website":["Clean Light","Ocean"]}[type]||["Clean Light","Ocean"]; const tr=$(`input[name="Theme"][value="${choice[0]}"]`); if(tr)tr.checked=true; const pb=$(`.palette-option[data-name="${choice[1]}"]`); if(pb)pb.click(); else updatePreview()});
  function snapshot(){return{brand:$("#brand-name").value,industry:$("#industry").value,tagline:$("#tagline").value,goal:$("#goal").value,type:selected("Website_Type"),theme:selected("Theme"),themeData:$("input[name='Theme']:checked")?.dataset.theme,font:selected("Font_Style"),fontData:$("input[name='Font_Style']:checked")?.dataset.font,size:selected("Text_Size"),sizeData:$("input[name='Text_Size']:checked")?.dataset.size,radius:selected("Corner_Style"),radiusData:$("input[name='Corner_Style']:checked")?.dataset.radius,motion:selected("Motion_Level"),motionData:$("input[name='Motion_Level']:checked")?.dataset.motion,palette:state.palette,bg:state.bg,primary:state.primary,accent:state.accent}}
  function saveDraft(){try{localStorage.setItem("icharles-website-studio-draft-v2",JSON.stringify(snapshot()))}catch(_){}}
  $("#open-preview").addEventListener("click",()=>{const s=snapshot(),brand=esc(s.brand||"YOUR BRAND"),industry=esc(s.industry||"YOUR BUSINESS"),tagline=esc(s.tagline||"Your message becomes clear, memorable and easy to act on.");const light=["light","minimal"].includes(s.themeData);const html=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${brand} — Concept</title><style>*{box-sizing:border-box}body{margin:0;background:${s.bg};color:${light?"#15191f":"#eef7ff"};font-family:${s.fontData==="serif"?"Georgia,serif":s.fontData==="mono"?"ui-monospace,Consolas,monospace":s.fontData==="friendly"?"Trebuchet MS,Arial,sans-serif":"Arial,sans-serif"}}header{height:78px;padding:0 6vw;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid ${s.primary}33}header b{letter-spacing:.08em}nav{display:flex;gap:24px;color:#7f8c9e;font-size:12px}.hero{min-height:calc(100vh - 78px);padding:12vh 8vw;position:relative;overflow:hidden}.hero:after{content:"";position:absolute;width:45vw;height:45vw;border:1px solid ${s.primary}55;border-radius:50%;right:-12vw;top:2vh;box-shadow:0 0 130px ${s.primary}18}.eyebrow{color:${s.primary};font-size:11px;letter-spacing:.13em}.hero h1{position:relative;z-index:2;max-width:1000px;font-size:clamp(58px,9vw,140px);line-height:.86;letter-spacing:-.06em;margin:25px 0}.hero h1 span{color:${s.primary}}.hero p{position:relative;z-index:2;max-width:650px;color:#8997aa;font-size:20px;line-height:1.6}.hero button{position:relative;z-index:2;margin-top:24px;padding:16px 20px;border:0;background:${s.primary};color:${s.bg};font-weight:900}small{position:fixed;right:18px;bottom:15px;color:#66758b;font:10px ui-monospace;letter-spacing:.08em}@media(max-width:700px){nav{display:none}.hero{padding:10vh 7vw}.hero h1{font-size:17vw}}</style></head><body><header><b>${brand}</b><nav><span>ABOUT</span><span>SERVICES</span><span>CONTACT</span></nav></header><section class="hero"><div class="eyebrow">${industry.toUpperCase()} // WEBSITE CONCEPT</div><h1>${brand}<br><span>ONLINE.</span></h1><p>${tagline}</p><button>START HERE →</button></section><small>CONCEPT PREVIEW BY CHARLES LIOC · NOT FINAL WEBSITE</small></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:"text/html"}));const win=window.open(url,"_blank","noopener");if(!win)location.href=url;setTimeout(()=>URL.revokeObjectURL(url),60000)});
  $("#reset-studio").addEventListener("click",()=>{if(!confirm("Reset your Website Studio choices?"))return;form.reset();state.bg="#070A10";state.primary="#00F0FF";state.accent="#8B5CFF";state.palette="Cyber Cyan";$$(".palette-option").forEach((x,i)=>x.classList.toggle("active",i===0));$("#color-bg").value=state.bg;$("#color-primary").value=state.primary;$("#color-accent").value=state.accent;applyRecommendation();showStep(1,false);try{localStorage.removeItem("icharles-website-studio-draft-v2")}catch(_){}});
  form.addEventListener("submit",e=>{updateSummary();if(!form.checkValidity()){e.preventDefault();form.reportValidity();return}const submit=$("#wizard-submit");submit.disabled=true;submit.querySelector("span").textContent="SENDING REQUEST...";try{localStorage.removeItem("icharles-website-studio-draft-v2")}catch(_){}});
  applyRecommendation(); updatePreview(); showStep(1,false);
})();